### ISSUE TITLE
Tomorrow Command Feature

### ISSUE THREAD

**Issue by 0x6F72656F73** [Et3rnos/ImaginaryCTF#1]
Request: A tomorrow command for board members that gives the challenge title if there a challenge approved for the next day and if not tells them to make a challenge.

**Comment by Et3rnos** [comment]
I can make it so that 30 minutes before the release, if no challenge is approved, a message is sent in board-chat telling board members to approve a challenge. Will that work?

**Comment by 0x6F72656F73** [comment]
Perfect. Thanks :)

**Comment by MatthewN-imaginary** [comment]
So someone has to speed run and approve or make a challenge in less than 30 minutes? Perfect idea

**Comment by 0x6F72656F73** [comment]
If you don't mind, can you make it send a message regardless if there isn't a challenge? That would be nice.

**Comment by Et3rnos** [comment]
Sure, that won't be a problem

**Comment by 0x6F72656F73** [comment]
Thanks for implementing.
