### ISSUE TITLE
Challenge category types

### ISSUE THREAD

**Issue by 0x6F72656F73** [Et3rnos/ImaginaryCTF#11]
To prevent <https://discord.com/channels/732308165265326080/732318949617696828/835268671504515092>, 
>  challenges listed as 'RE', 'Reversing', 'Reverse Engineering'

It would be nice to have some type of selection for typical categories such as a dropdown, with an other's option for nonstandard categories.

Categories I'm thinking right now are:

- Crypto
- Web
- Reversing
- Pwn
- Forensics
- Misc
  - Pyjail
  - Pwn
  - Crypto
  - Web
  - Forensics
  - Reversing
  - Programming

Thanks :P

**Comment by Et3rnos** [comment]
Implemented something similar
