### ISSUE TITLE
add feature that shows solves for each challenge next to challenge + more stats

### ISSUE THREAD

**Issue by madmax49** [Et3rnos/ImaginaryCTF#13]
A website feature that would show total solves for each challenge and possibly the number of attempted solves, like:

({correct flag submissions} solves/{total flag submissions} total attempts)

Though I don't know if it's possible to get total submissions from the website + bot combined, it would be cool to get this statistic.

(this feature would be similar to how pico handles challenges)

**Comment by Et3rnos** [comment]
I'm planning to do that but it will require some changes in the database organization, so it can take a month or two until it comes out, as it is better for database changes to only occur at the end of the rounds

**Comment by Et3rnos** [comment]
Implemented :)
