### ISSUE TITLE
maybe add the ability to translate the website on the press of a button/based on browser locale settings

### ISSUE THREAD

**Issue by max-49** [Et3rnos/ImaginaryCTF#36]
We have a lot of people in the ictf server that could help with translations. Might be annoying to implement though so I understand if this gets dropped lol.

**Comment by Et3rnos** [comment]
I think it's too early for me to implement this. However, I'll let this open because it would be a nice feature to have in the future

**Comment by Et3rnos** [comment]
I'm gonna close this for now
