### ISSUE TITLE
Make different channels for each challenge day

### ISSUE THREAD

**Issue by 4nimanegra** [Et3rnos/ImaginaryCTF#43]
Still now, if you solved a challenge on the same you are able to talk about different solution approaches with other users. By my point of view is one of the most educating parts of the discord.
It could be marvelous having different channels that opens when you solve one challenge, and then be able to see the other solutions and be able to talk about them with others.

PS: The site is fucking amazing thanks for all the work the staff make everyday.

**Comment by Et3rnos** [comment]
It has been implemented in the meanwhile, so I'm closing this issue :)
