### ISSUE TITLE
Bot welcome message

### ISSUE THREAD

**Issue by Matthew-Imaginary** [Et3rnos/ImaginaryCTF#5]
When a user joins the discord server, have it put a welcome message in two different channels, one they can see before they verify and one after, the message would be worded different

**Comment by Et3rnos** [comment]
Can you please expain the differences between both welcome messages?

**Comment by MatthewN-imaginary** [comment]
One would tell them to read the rules and react in #welcome-readme, the other one would tell them more info like to read the #faq and to go look at challenges in ctf challenge

**Comment by Et3rnos** [comment]
I don't really want to have the bot sending 2 welcome messages so I'll try to create a welcome message that combines those 2 ideas
